name: 'Setup Pulsar Action'
description: 'Setup a Pulsar Server'

runs:
  using: 'composite'
  steps:
    - name: start pulsar
      run: bash $GITHUB_ACTION_PATH/start_pulsar.sh
      shell: bash
    - name: wait pulsar start
      uses: shoothzj/host-available-check-action@v1
      with:
        check_type: 'HTTP'
        check_timeout: 60
        check_http_port: 8080
        check_http_path: '/admin/v2/brokers/health'
